ThAmCo.Events/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ThAmCo.Events.Data;
using ThAmCo.Events.Models;

namespace ThAmCo.Events.Controllers
{
    public class EventController : Controller
    {
        private readonly EventsDbContext _context;

        public EventController(EventsDbContext context)
        {
            _context = context;
        }

        // GET: Events
        public async Task<IActionResult> Index()
        {
            return View(await _context.Events.ToListAsync());
        }

        // GET: Events/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Events
                .Include(s => s.Staffing)
                .ThenInclude(s => s.Staff)
                .Include(g => g.Bookings)
                .ThenInclude(c => c.Customer)
                .FirstOrDefaultAsync(m => m.Id == id);

            var venues = new List<EventVenueDto>().AsEnumerable();
            String eventType = @event.TypeId;
            DateTime beginDate = @event.Date;
            DateTime endDate = @event.Date.Add(@event.Duration.Value);

            HttpClient client = new HttpClient();
            client.BaseAddress = new System.Uri("http://localhost:23652/");

            HttpResponseMessage response = await client.GetAsync("api/Availability?eventType=" + eventType
                + "&beginDate=" + beginDate.ToString("yyyy-MM-dd") +
                "&endDate=" + endDate.ToString("yyyy-MM-dd"));

            EventVenueDto venue = null;

            if (response.IsSuccessStatusCode)
            {
                venues = await response.Content.ReadAsAsync<IEnumerable<EventVenueDto>>();
                if (venues.Count() == 0)
                {
                    ViewBag.NullVenues = true;
                    Debug.WriteLine("No items");
                }
                else
                {
                    bool found = false;
                    foreach(var ven in venues)
                    {
                        if(ven.Code == @event.VenueCode)
                        {
                            venue = ven;
                            found = true;
                            break;
                        }
                    }
                    if(!found)
                    {
                        ViewBag.NullVenues = true;
                        Debug.WriteLine("No items");
                    }
                }
            }
            else
            {
                return BadRequest();
            }

            if (@event == null)
            {
                return NotFound();
            }

            var model = new VenueAndEventModel();
            model.Event = @event;
            model.Venue = venue;
            return View(model);
        }

        public async Task<IActionResult> StaffingDetails(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @staffing = await _context.Staffing
                .FirstOrDefaultAsync(e => e.EventId == id);

            if (@staffing == null)
            {
                ViewBag.NoStaff = true;
                staffing = new Staffing();
                staffing.EventId = id.Value;
                staffing.Event = await _context.
                    Events.FirstOrDefaultAsync(e => e.Id == id);
                Debug.WriteLine("No staff");
            }

            ViewBag.Staffing = true;

            return View("_StaffList", staffing);
        }

        // GET: Events/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Events/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Date,Duration,TypeId")] Event @event)
        {
            if (ModelState.IsValid)
            {
                _context.Add(@event);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(@event);
        }

        // GET: Events/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Events.FindAsync(id);
            if (@event == null)
            {
                return NotFound();
            }
            return View(@event);
        }

        // POST: Events/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Date,Duration,TypeId")] Event @event)
        {
            if (id != @event.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var model = await _context.Events.FindAsync(id);
                    model.Title = @event.Title;
                    model.Duration = @event.Duration;
                    _context.Update(model);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventExists(@event.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(@event);
        }

        // GET: Events/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Events
                .FirstOrDefaultAsync(m => m.Id == id);
            if (@event == null)
            {
                return NotFound();
            }

            return View(@event);
        }

        // POST: Events/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var @event = await _context.Events.FindAsync(id);
            _context.Events.Remove(@event);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EventExists(int id)
        {
            return _context.Events.Any(e => e.Id == id);
        }
        public async Task<IActionResult> ChooseVenue(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var curEvent = await _context.Events.FirstOrDefaultAsync(m => m.Id == id);
                                         //.Where(e => e.isActive)
            if (curEvent == null)
            {
                return BadRequest();
            }

            String eventType = curEvent.TypeId;
            DateTime beginDate = curEvent.Date;
            DateTime endDate = curEvent.Date.Add(curEvent.Duration.Value);

            var availableVenues = new List<ChooseVenueDto>().AsEnumerable();

            HttpClient client = new HttpClient();
            client.BaseAddress = new System.Uri("http://localhost:23652/");

            HttpResponseMessage response = await client.GetAsync("api/Availability?eventType=" + eventType
                + "&beginDate=" + beginDate.ToString("yyyy-MM-dd") +
                "&endDate=" + endDate.ToString("yyyy-MM-dd"));

            if (response.IsSuccessStatusCode)
            {
                availableVenues = await response.Content.ReadAsAsync<IEnumerable<ChooseVenueDto>>();

                if (availableVenues.Count() == 0)
                {
                    ViewBag.NullVenues = true;
                    Debug.WriteLine("No items");
                }
            }
            else
            {
                Debug.WriteLine("Received a bad response from the web service.");
                return BadRequest();
            }

            ViewData["EventTitle"] = curEvent.Title;
            ViewData["EventId"] = curEvent.Id;
            ViewData["EventDate"] = curEvent.Date;

            return View(availableVenues);
        }

        public async Task<IActionResult> ReserveVenue(int EventId, DateTime EventDate, string VenueCode)
        {
            if (EventDate == null || VenueCode == null)
            {
                return NotFound();
            }

            var curEvent = await _context.Events
                                         .FirstOrDefaultAsync(m => m.Id == EventId);

            if (curEvent == null)
            {
                return BadRequest();
            }

            HttpClient client = new HttpClient();
            client.BaseAddress = new System.Uri("http://localhost:23652/");

            var reservation = new ReservationPostDto
            {
                EventDate = EventDate,
                VenueCode = VenueCode,
            };

            if (!String.IsNullOrEmpty(curEvent.VenueCode))
            {
                var reference = curEvent.VenueCode + EventDate.ToString("yyyy-MM-dd");
                await client.DeleteAsync("api/reservations/" + reference);
            }

ThAmCo.Events/Controllers/StaffController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ThAmCo.Events.Data;

namespace ThAmCo.Events.Controllers
{
    public class StaffController : Controller
    {
        private readonly EventsDbContext _context;

        public StaffController(EventsDbContext context)
        {
            _context = context;
        }

        // GET: Staff
        public async Task<IActionResult> Index()
        {
            return View(await _context.Staff.ToListAsync());
        }

        // GET: Staff/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var staff = await _context.Staff
                .FirstOrDefaultAsync(m => m.Id == id);
            if (staff == null)
            {
                return NotFound();
            }

            return View(staff);
        }

        // GET: Staff/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Staff/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirstName,Surname,Firstaider")] Staff staff)
        {
            if (ModelState.IsValid)
            {
                _context.Add(staff);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(staff);
        }

        // GET: Staff/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var staff = await _context.Staff.FindAsync(id);
            if (staff == null)
            {
                return NotFound();
            }
            return View(staff);
        }

        // POST: Staff/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,Surname,Firstaider")] Staff staff)
        {
            if (id != staff.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(staff);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StaffExists(staff.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(staff);
        }

        // GET: Staff/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var staff = await _context.Staff
                .FirstOrDefaultAsync(m => m.Id == id);
            if (staff == null)
            {
                return NotFound();
            }

            return View(staff);
        }

        // POST: Staff/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var staff = await _context.Staff.FindAsync(id);
            _context.Staff.Remove(staff);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StaffExists(int id)
        {
            return _context.Staff.Any(e => e.Id == id);
        }
    }
}

ThAmCo.Events/Views/Staffing/Create.cshtml
@model ThAmCo.Events.Data.Staffing

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Staffing</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="StaffId" class="control-label"></label>
                <select asp-for="StaffId" class ="form-control" asp-items="ViewBag.StaffId"></select>
            </div>
            <div class="form-group">
                <label asp-for="EventId" class="control-label"></label>
                <select asp-for="EventId" class ="form-control" asp-items="ViewBag.EventId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ThAmCo.Events/Views/Staffing/Delete.cshtml
@model ThAmCo.Events.Data.Staffing

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Staffing</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Staff)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Staff.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Event)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Event.Title)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="StaffId" />
        <input type="hidden" asp-for="EventId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-controller="Event" asp-action="Index">Back to Events</a>
    </form>
</div>

ThAmCo.Events/Views/Staffing/Details.cshtml
@model ThAmCo.Events.Data.Staffing

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Staffing</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Staff)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Staff.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Event)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Event.Title)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

ThAmCo.Events/Views/Staffing/Edit.cshtml
@model ThAmCo.Events.Data.Staffing

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Staffing</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="StaffId" />
            <input type="hidden" asp-for="EventId" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ThAmCo.Events/Views/Staffing/EventIndex.cshtml
@model IEnumerable<ThAmCo.Events.Data.Staffing>

@{
    ViewData["Title"] = "Staffing";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Add Staff</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Staff)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Event)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Staff.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Event.Title)
            </td>
            <td>
                @Html.ActionLink("Details","Details", "Staff", new {  id=item.StaffId }) |
                @Html.ActionLink("Delete", "Delete", new {  id=item.StaffingId  })
            </td>
        </tr>
}
    </tbody>
</table>

ThAmCo.Events/Views/Staffing/Index.cshtml
@model IEnumerable<ThAmCo.Events.Data.Staffing>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Staff)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Event)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Staff.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Event.Title)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>